### PR TITLE
Implemented get_nominees, find_tweets_about, find_imdb_movie

### PR DESCRIPTION
**Pull request by MarkoSterbentz**

### CODE REVIEW

**Comment by MarkoSterbentz** [comment]
I just resolved the merge conflict. For some reason the fuzzy match function was conflicting with one of the functions I wrote. I left the IMDb function in there for now, but we can remove it later.

**Comment by barrieca** [comment]
It still says that there's conflicting files. I wonder if you need to create a new pull request.

**Comment by MarkoSterbentz** [comment]
There were new conflicts since Alex's branch had gotten merged into master. I've resolved those by integrating my functions into the base branch now. It should be good to go now.

**Comment by barrieca** [comment]
Hmmmm. Still showing merge conflicts.

**Comment by AlexanderEinarsson** [comment]
That might be on me. I needed to change a line, so I pushed straight to
master. Is the conflict a line that contains the (non-existent) function
.contains?

**Comment by AlexanderEinarsson** [comment]
That might be on me. I needed to change a line, so I pushed straight to
master. Is the conflict a line that contains the (non-existent) function
.contains?

If so, just steamroll it, and we'll fix that line after.

**Comment by MarkoSterbentz** [comment]
I merged the change Alex made with my branch. I also added a .gitattributes file that's supposed to configure line endings for us, since I'm pretty sure that's making the diff's really messy. There might be more have to do to actually configure that though. Regardless, the branch should finally be ready to merge.

**Comment by AlexanderEinarsson** [comment]
Merged it.

**Pull request merged**
